"use client";

import { useCallback } from "react";

interface ExportPDFProps {
  task: string;
  privacyScore: number;
  fieldsHidden: number;
  fieldsRevealed: number;
  intentCategory: string;
  cost: number;
  logEntries: Array<{ time: string; action: string; type: string; detail?: string }>;
  manifest: any;
  execution: any;
}

export function ExportPDF(props: ExportPDFProps) {
  const handleExport = useCallback(async () => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    const { task, privacyScore, fieldsHidden, fieldsRevealed, intentCategory, cost, logEntries, manifest, execution } = props;

    let y = 20;
    const addLine = (text: string, size = 10, color = "#FAFAFA") => {
      doc.setFontSize(size);
      doc.setTextColor(color);
      doc.text(text, 20, y);
      y += size * 0.5 + 2;
    };
    const addGap = (gap = 5) => { y += gap; };

    // Background
    doc.setFillColor(9, 9, 11);
    doc.rect(0, 0, 210, 297, "F");

    // Header
    doc.setFontSize(20);
    doc.setTextColor("#D4A853");
    doc.text("SHADE", 20, y);
    doc.setFontSize(8);
    doc.setTextColor("#52525B");
    doc.text("Privacy-Preserving Agent Report", 50, y);
    y += 12;

    // Divider
    doc.setDrawColor("#27272A");
    doc.line(20, y, 190, y);
    y += 8;

    // Task
    addLine("TASK", 8, "#52525B");
    addLine(task.length > 80 ? task.slice(0, 80) + "..." : task, 11, "#FAFAFA");
    addGap();

    // Privacy Summary
    addLine("PRIVACY SUMMARY", 8, "#52525B");
    addLine(`Privacy Score: ${privacyScore}%`, 11, "#D4A853");
    addLine(`Fields Hidden: ${fieldsHidden}  |  Fields Revealed: ${fieldsRevealed}`, 10, "#A1A1AA");
    addLine(`Intent Category: ${intentCategory}`, 10, "#A1A1AA");
    const costDisplay = intentCategory === "payment"
      ? `$${(cost < 0.0001 ? cost * 1e12 : cost).toFixed(2)} USDC`
      : cost > 0 ? `${cost} ETH` : "—";
    addLine(`Cost: ${costDisplay}`, 10, "#A1A1AA");
    addGap();

    // Execution
    if (execution) {
      addLine("EXECUTION", 8, "#52525B");
      addLine(`Method: ${execution.method === "locus" ? "Locus" : "ShadeVault"}`, 10, "#A1A1AA");
      addLine(`Status: ${execution.success ? "Success" : "Failed"}`, 10, execution.success ? "#22C55E" : "#EF4444");
      if (execution.txHash) {
        addLine(`TX: ${execution.txHash}`, 8, "#52525B");
      }
      if (execution.error) {
        addLine(`Error: ${execution.error.slice(0, 60)}`, 9, "#EF4444");
      }
      addGap();
    }

    // Disclosure Manifest
    if (manifest) {
      addLine("DISCLOSURE MANIFEST", 8, "#52525B");
      addLine(`Identity: ${manifest.identity?.status?.toUpperCase() || "HIDDEN"}`, 10, "#22C55E");
      addLine(`Wallet: ${manifest.wallet?.type?.toUpperCase() || "EPHEMERAL"}`, 10, "#22C55E");
      addLine(`Budget: ${manifest.budget?.status?.toUpperCase() || "HIDDEN"}${manifest.budget?.revealed ? ` (${manifest.budget.revealed})` : ""}`, 10, "#A1A1AA");
      addLine(`Intent: ${manifest.intent?.status?.toUpperCase() || "HIDDEN"}${manifest.intent?.revealed ? ` (${manifest.intent.revealed})` : ""}`, 10, "#A1A1AA");
      addLine(`IP: STRIPPED  |  Device: STRIPPED  |  Session: UNLINKED`, 10, "#22C55E");
      addGap();
    }

    // Activity Log
    addLine("ACTIVITY LOG", 8, "#52525B");
    y += 2;
    for (const entry of logEntries.slice(0, 15)) {
      if (y > 270) break;
      const detail = entry.detail ? ` (${entry.detail})` : "";
      const text = `[${entry.time}] ${entry.action}${detail}`;
      addLine(text.length > 85 ? text.slice(0, 85) + "..." : text, 8, "#A1A1AA");
    }

    // Footer
    y = 285;
    doc.setDrawColor("#27272A");
    doc.line(20, y - 5, 190, y - 5);
    doc.setFontSize(7);
    doc.setTextColor("#52525B");
    doc.text("Generated by Shade Agent v1.0  |  Privacy-Preserving Autonomous Agent  |  ERC-8004 #2321", 20, y);

    doc.save(`shade-report-${Date.now()}.pdf`);
  }, [props]);

  return (
    <button
      data-export-pdf
      onClick={handleExport}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg glass font-mono text-[11px] text-text-3 hover:text-gold transition-colors cursor-pointer"
    >
      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      Export PDF
    </button>
  );
}
